### ISSUE TITLE
Ensure 'subject' is unique in the metadata registry

### ISSUE THREAD

**Issue by mrwol5** [input-output-hk/metadata-server#34]
It appears one can submit multiple sets of mappings for the same subject by altering the filename of the submission. Please see here an example of two records for the same subject on metadata-registry-testnet:

https://github.com/input-output-hk/metadata-registry-testnet/blob/master/registry/caa836fef09cb35e180fce4b55ded152907af1e2c840ed5218776f2f.json

https://github.com/input-output-hk/metadata-registry-testnet/blob/master/registry/baa836fef09cb35e180fce4b55ded152907af1e2c840ed5218776f2f.json

Perhaps CI should be also validating that the filename and 'subject' match.

**Comment by sevanspowell** [comment]
Thanks for the helpful suggestion, I've opened a fix here: https://github.com/input-output-hk/metadata-server/pull/36

**Comment by sevanspowell** [comment]
This fix has been deployed to testnet, I've re-run your job and you can see the (expected) failure here: https://github.com/input-output-hk/metadata-registry-testnet/runs/2028545981

Thanks!
