### ISSUE TITLE
Add CI check for modification of appropriate folder

### ISSUE THREAD

**Issue by mrwol5** [input-output-hk/metadata-server#40]
Tests should fail if the PR does not modify a predefined folder (eg registry/ or mappings/) - we do not want users to modify other folders or create their own. Will help reduce manual work for the operators.

**Comment by disassembler** [comment]
We can probably do this in the GH action itself rather than needing the validator to support it.

**Comment by johnalotoski** [comment]
Yes, we can implement this in the github action, along with some basic filename validation, see for example the output [here](https://github.com/input-output-hk/metadata-registry-testnet/runs/2040554018?check_suite_focus=true).

**Comment by johnalotoski** [comment]
Done and committed to the registry repos (ex: https://github.com/cardano-foundation/cardano-token-registry/commit/df5ddaf0284f4837234e93ab847c07f6e8b11277).  Please re-open if an outstanding problem around this remains.
